name: snaplook
description: "A Flutter app for fashion detection and styling recommendations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI Components
  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2780.0

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1

  # Database
  supabase_flutter: ^2.6.0

  # Image Processing
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  cached_network_image: ^3.3.1

  # Camera & Media
  camera: ^0.11.0+2
  photo_manager: ^3.2.3

  # Social Media Integration
  url_launcher: ^6.3.0
  share_plus: ^10.0.2

  # File Handling
  path_provider: ^2.1.4
  file_picker: ^8.1.2

  # Storage & Preferences
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Animations & UI
  animate_do: ^3.3.4
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700