/// 🔠 Category rules and overrides for garment classification.
/// Used in DetectionService._categorize() to map product titles to standard categories.

const Map<String, List<String>> kCategoryKeywords = {
  'dresses': [
    'dress',
    'gown',
    'jumpsuit',
    'romper',
    'one-piece',
    'one piece',
    'bodysuit',
    'maxi dress',
    'midi dress',
    'mini dress',
    'evening dress',
    'cocktail dress',
  ],
  'tops': [
    'top',
    'shirt',
    't-shirt',
    'tee',
    'tank',
    'blouse',
    'polo',
    'sweater',
    'hoodie',
    'crewneck',
    'jumper',
    'camisole',
    'cardigan',
    'tunic',
  ],
  'bottoms': [
    'jeans',
    'pants',
    'trouser',
    'shorts',
    'skirt',
    'leggings',
    'cargo',
    'chino',
    'culotte',
    'sweatpants',
    'jogger',
    'denim',
  ],
  'outerwear': [
    'coat',
    'jacket',
    'blazer',
    'vest',
    'trench',
    'puffer',
    'windbreaker',
    'parka',
    'anorak',
    'raincoat',
  ],
  'shoes': [
    'shoe',
    'sneaker',
    'boot',
    'heel',
    'loafer',
    'flat',
    'sandal',
    'slipper',
    'moccasin',
    'trainer',
    'wedge',
    'platform',
    'flip-flop',
    'clog',
    'oxford',
    'derby',
  ],
  'bags': [
    'bag',
    'handbag',
    'tote',
    'crossbody',
    'backpack',
    'satchel',
    'clutch',
    'duffel',
    'wallet',
    'purse',
    'briefcase',
  ],
  'headwear': [
    'hat',
    'cap',
    'beanie',
    'beret',
    'visor',
    'bucket hat',
    'headband',
  ],
  'accessories': [
    'scarf',
    'belt',
    'glasses',
    'sunglasses',
    'watch',
    'earring',
    'necklace',
    'bracelet',
    'ring',
    'tie',
    'bowtie',
    'pin',
    'brooch',
    'glove',
    'keychain',
  ],
};

/// 🧠 Context-aware overrides for ambiguous terms.
/// These are matched as lowercase substrings in titles before keyword detection.
const Map<String, String> kCategoryOverrides = {
  // --- Bottoms overrides ---
  'dress pants': 'bottoms',
  'trousers': 'bottoms',
  'chinos': 'bottoms',
  'cargo pants': 'bottoms',
  'sweatpants': 'bottoms',

  // --- Dresses overrides ---
  'jumpsuit': 'dresses',
  'romper': 'dresses',
  'one piece': 'dresses',
  'bodysuit': 'dresses',

  // --- Shoes overrides ---
  'high top': 'shoes',
  'low top': 'shoes',
  'running shoe': 'shoes',
  'tennis shoe': 'shoes',
  'trainers': 'shoes',
  'slides': 'shoes',
  'flip flop': 'shoes',
  'crocs': 'shoes',

  // --- Outerwear overrides ---
  'denim jacket': 'outerwear',
  'leather jacket': 'outerwear',
  'bomber jacket': 'outerwear',
  'varsity jacket': 'outerwear',

  // --- Accessories overrides ---
  'eyewear': 'accessories',
  'sunglass': 'accessories',
  'handkerchief': 'accessories',
  'keychain': 'accessories',
  'wallet': 'accessories',
  'watch': 'accessories',
  'cap': 'headwear',
};

/// 🚫 Stopwords ignored when extracting brand or title tokens.
const Set<String> kCategoryStopWords = {
  'the',
  'and',
  'with',
  'for',
  'from',
  'by',
  'men',
  'women',
  'kids',
  'unisex',
  'fashion',
  'style',
  'clothing',
  'apparel',
  'brand',
  'store',
  'shop',
  'official',
  'new',
  'sale',
  'discount',
};
