/// Trusted and banned domains for DetectionService filtering.
/// Used to validate ecommerce links from SerpAPI or other image search engines.

const List<String> kTrustedDomains = [
  // --- Global / marketplaces ---
  'amazon.',
  'ebay.',
  'etsy.',
  'walmart.',
  'target.',
  'aliexpress.',
  'alibaba.',
  'rakuten.',
  'jd.com',
  'flipkart.',
  'shopee.',
  'lazada.',
  'noon.',
  'bol.com',
  'zalora.',
  'zalando.',

  // --- Fashion & apparel ---
  'asos.',
  'zara.',
  'hm.',
  'mango.',
  'shein.',
  'boohoo.',
  'princesspolly.',
  'prettyLittleThing.',
  'fashionnova.',
  'nastygal.',
  'revolve.',
  'ssense.',
  'farfetch.',
  'uniqlo.',
  'madewell.',
  'everlane.',
  'reformation.',
  'urbanoutfitters.',
  'anthropologie.',
  'freepeople.',
  'aritzia.',
  'garageclothing.',
  'lulus.',
  'na-kd.',
  'cottonon.',
  'showpo.',
  'beginningboutique.',
  'tobi.',
  'missguided.',
  'windsorstore.',
  'boozt.',
  'cos.',
  'weekday.',
  'monki.',
  'bershka.',
  'pullandbear.',
  'stradivarius.',
  'massimodutti.',
  'primark.',
  'only.com',
  'jackjones.',

  // --- Premium & designer ---
  'ralphlauren.',
  'calvinklein.',
  'tommy.com',
  'armaniexchange.',
  'apc.',
  'kenzo.',
  'marcjacobs.',
  'dsquared2.',
  'ragandbone.',
  'balmain.',
  'rickowens.',
  'proenzaschouler.',
  'miumiu.',
  'loewe.',
  'maisonmargiela.',
  'zegna.',
  'lanvin.',
  'valentino.',
  'prada.',
  'gucci.',
  'burberry.',
  'ysl.',
  'celine.',
  'fendi.',
  'bottegaveneta.',
  'louisvuitton.',
  'balenciaga.',
  'brunellocucinelli.',
  'saintlaurent.',

  // --- Luxury retailers ---
  'mytheresa.',
  'matchesfashion.',
  'net-a-porter.',
  'mrporter.',
  'theoutnet.',
  'harrods.',
  'selfridges.',
  'brownsfashion.',
  'bergdorfgoodman.',
  'saksfifthavenue.',
  'neimanmarcus.',
  'nordstrom.',
  'bloomingdales.',
  'macys.',
  'harveynichols.',
  '24s.com',
  'luisaViaRoma.',
  'italist.',
  'modaoperandi.',
  'fwrd.',
  'shopbop.',
  'endclothing.',

  // --- Sportswear / activewear ---
  'nike.',
  'adidas.',
  'puma.',
  'reebok.',
  'newbalance.',
  'asics.',
  'vans.',
  'converse.',
  'underarmour.',
  'lululemon.',
  'gymshark.',
  'fabletics.',
  'aloyoga.',
  'outdoorvoices.',
  'patagonia.',
  'northface.',
  'columbia.',
  'on-running.',
  'salomon.',
  'merrell.',
  'teva.',
  'hoka.',

  // --- Footwear & sneakers ---
  'crocs.',
  'birkenstock.',
  'drmartens.',
  'footlocker.',
  'finishline.',
  'goat.',
  'stockx.',
  'snipes.',
  'jd-sports.',
  'champssports.',

  // --- Jewelry / watches / accessories ---
  'pandora.',
  'tiffany.',
  'cartier.',
  'rolex.',
  'tagheuer.',
  'omega.',
  'bulgari.',
  'breitling.',
  'longines.',
  'fossil.',
  'danielwellington.',
  'mvmt.',
  'swarovski.',
  'skagen.',
  'citizenwatch.',
  'seikowatches.',
  'cluse.',
  'apmmonaco.',

  // --- Eyewear ---
  'ray-ban.',
  'warbyparker.',
  'zennioptical.',
  'eyebuydirect.',
  'oakley.',
  'persol.',
  'mauijim.',
  'glassesusa.',
  'sunglasshut.',
  'smartbuyglasses.',

  // --- Bags & luggage ---
  'samsonite.',
  'tumi.',
  'awaytravel.',
  'rimowa.',
  'kipling.',
  'longchamp.',
  'coach.',
  'michaelkors.',
  'katespade.',
  'guess.',
  'dooney.',
  'toryburch.',
  'herschel.',
  'eastpak.',
  'jansport.',

  // --- Sustainable / indie brands ---
  'pactwear.',
  'tentree.',
  'girlfriendcollective.',
  'organicbasics.',
  'kotn.',
  'matethelabel.',
  'theslowlabel.',
  'cuyana.',
  'allbirds.',

  // --- Department stores / regionals ---
  'marksandspencer.',
  'houseoffraser.',
  'johnlewis.',
  'debenhams.',
  'myer.',
  'davidjones.',
  'century21stores.',
  'lordandtaylor.',
  'boscovs.',
  'argos.',
  'boots.',
  'very.co.uk',
  'next.co.uk',
  'next.',
  'peek-cloppenburg.',
  'galerieslafayette.',
  'otto.de',
  'aboutyou.',
  'bonprix.',

  // --- Resale / luxury marketplaces ---
  'vestiairecollective.',
  'grailed.',
  'theRealReal.',
  'rebag.',
  'vinted.',
  'poshmark.',
  'depop.',
  'thredup.',

  // --- Beauty & skincare (fashion adjacent) ---
  'sephora.',
  'ulta.',
  'glossier.',
  'lookfantastic.',
  'cultbeauty.',
  'elfcosmetics.',
  'fentybeauty.',
  'rarebeauty.',
  'morphe.',
  'kyliecosmetics.',
  'hudabeauty.',
  'charlottetilbury.',
  'narscosmetics.',
  'mac-cosmetics.',
  'clinique.',
  'lancome.',
  'diorbeauty.',
  'chanelbeauty.',
  'shiseido.',
  'loreal.',
];

/// Non-ecommerce domains to ignore or filter out.
/// These are blogs, magazines, social media, content farms,
/// tech sites, and non-shoppable sources that can appear in Google Lens results.
const List<String> kBannedDomains = [
  // --- Social media & community platforms ---
  'facebook.',
  'instagram.',
  'twitter.',
  'x.com',
  'pinterest.',
  'tiktok.',
  'linkedin.',
  'reddit.',
  'youtube.',
  'snapchat.',
  'threads.',
  'discord.',
  'wechat.',
  'weibo.',
  'line.me',
  'vk.com',

  // --- Blogging platforms & generic CMS hosts ---
  'blogspot.',
  'wordpress.',
  'tumblr.',
  'medium.',
  'substack.',
  'weebly.',
  'wixsite.',
  'squarespace.',
  'ghost.io',
  'notion.site',
  'blog.',
  'livejournal.',
  'typepad.',

  // --- Knowledge / reference sites ---
  'quora.',
  'fandom.',
  'wikipedia.',
  'wikihow.',
  'britannica.',
  'stackexchange.',
  'stackoverflow.',
  'ask.com',
  'answers.com',

  // --- News / media outlets ---
  'bbc.',
  'cnn.',
  'nytimes.',
  'washingtonpost.',
  'forbes.',
  'bloomberg.',
  'reuters.',
  'huffpost.',
  'usatoday.',
  'abcnews.',
  'cbsnews.',
  'npr.',
  'time.',
  'theguardian.',
  'independent.co.uk',
  'theatlantic.',
  'vox.',
  'buzzfeed.',
  'vice.',
  'msn.',
  'dailymail.',
  'mirror.co.uk',
  'nbcnews.',
  'latimes.',

  // --- Creative & art sharing platforms ---
  'goodreads.',
  'soundcloud.',
  'deviantart.',
  'dribbble.',
  'artstation.',
  'behance.',
  'vimeo.',
  'bandcamp.',
  'mixcloud.',
  'last.fm',
  'spotify.',

  // --- Editorial fashion & lifestyle media (non-shoppable) ---
  'vogue.',
  'elle.',
  'harpersbazaar.',
  'cosmopolitan.',
  'glamour.',
  'refinery29.',
  'whowhatwear.',
  'instyle.',
  'graziamagazine.',
  'vanityfair.',
  'marieclaire.',
  'teenvogue.',
  'stylecaster.',
  'popsugar.',
  'bazaar.',
  'nylon.',
  'lifestyleasia.',
  'femalemag.',
  'thezoereport.',
  'allure.',
  'coveteur.',
  'thecut.',
  'dazeddigital.',
  'highsnobiety.',
  'hypebeast.',
  'complex.',
  'gq.',
  'esquire.',
  'menshealth.',
  'wmagazine.',
  'people.',
  'entertainmentweekly.',
  'today.com',
  'insider.',
  'observer.',
  'standard.co.uk',
  'eveningstandard.',
  'nssmag.',
  'grazia.',

  // --- Travel / non-fashion ---
  'tripadvisor.',
  'expedia.',
  'lonelyplanet.',
  'booking.com',
  'airbnb.',
  'travelandleisure.',
  'kayak.',
  'skyscanner.',

  // --- Tech & gadget sites ---
  'techcrunch.',
  'wired.',
  'theverge.',
  'engadget.',
  'gsmarena.',
  'cnet.',
  'zdnet.',
  'mashable.',
  'makeuseof.',
  'arstechnica.',
  'androidauthority.',
  'macrumors.',
  '9to5mac.',
  'digitaltrends.',
  'imore.',
  'tomsguide.',
  'pocketlint.',

  // --- Generic aggregators / spammy directories ---
  'dealmoon.',
  'pricegrabber.',
  'shopmania.',
  'shoppingcomparison.',
  'trustpilot.',
  'reviewcentre.',
  'mouthshut.',
  'sitejabber.',
  'alibaba-blog.',
  'fashionista.',
  'lookbook.nu',
  'polyvore.',
  'stylebistro.',
  'redbubble.',
  'society6.',
  'teepublic.',
  'zazzle.',
  'spreadshirt.',
  'cafepress.',
  'etsyblog.',
  'depopblog.',
  'medium.com/@',
  'tistory.',
  'naver.blog.',

  // --- Forums & resale without commerce intent ---
  'reddit.',
  '4chan.',
  '8kun.',
  'thefashionspot.',
  'lookbook.nu',
  'styleforum.',
  'superfuture.',
  'archive.org',

  // --- Misc ---
  'patreon.',
  'onlyfans.',
  'ko-fi.',
  'buymeacoffee.',
  'pixiv.',
  'fanfiction.',
  'tumgir.',
];
