/// Trusted and banned domains for DetectionService filtering.
/// Used to validate ecommerce links from SerpAPI or other image search engines.

const List<String> kTrustedDomains = [
  // --- Global / marketplaces ---
  'amazon.',
  'ebay.',
  'etsy.',
  'walmart.',
  'target.',
  'aliexpress.',
  'alibaba.',
  'rakuten.',
  'jd.com',
  'flipkart.',
  'shopee.',
  'lazada.',
  'noon.',
  'bol.com',
  'zalora.',
  'zalando.',

  // --- Fashion & apparel ---
  'asos.',
  'zara.',
  'hm.',
  'mango.',
  'shein.',
  'boohoo.',
  'princesspolly.',
  'prettyLittleThing.',
  'fashionnova.',
  'nastygal.',
  'revolve.',
  'ssense.',
  'farfetch.',
  'uniqlo.',
  'madewell.',
  'everlane.',
  'reformation.',
  'urbanoutfitters.',
  'anthropologie.',
  'freepeople.',
  'aritzia.',
  'garageclothing.',
  'lulus.',
  'na-kd.',
  'cottonon.',
  'showpo.',
  'beginningboutique.',
  'tobi.',
  'missguided.',
  'windsorstore.',
  'boozt.',
  'cos.',
  'weekday.',
  'monki.',
  'bershka.',
  'pullandbear.',
  'stradivarius.',
  'massimodutti.',
  'primark.',
  'only.com',
  'jackjones.',

  // --- Premium & designer ---
  'ralphlauren.',
  'calvinklein.',
  'tommy.com',
  'armaniexchange.',
  'apc.',
  'kenzo.',
  'marcjacobs.',
  'dsquared2.',
  'ragandbone.',
  'balmain.',
  'rickowens.',
  'proenzaschouler.',
  'miumiu.',
  'loewe.',
  'maisonmargiela.',
  'zegna.',
  'lanvin.',
  'valentino.',
  'prada.',
  'gucci.',
  'burberry.',
  'ysl.',
  'celine.',
  'fendi.',
  'bottegaveneta.',
  'louisvuitton.',
  'balenciaga.',
  'brunellocucinelli.',
  'saintlaurent.',

  // --- Luxury retailers ---
  'mytheresa.',
  'matchesfashion.',
  'net-a-porter.',
  'mrporter.',
  'theoutnet.',
  'harrods.',
  'selfridges.',
  'brownsfashion.',
  'bergdorfgoodman.',
  'saksfifthavenue.',
  'neimanmarcus.',
  'nordstrom.',
  'bloomingdales.',
  'macys.',
  'harveynichols.',
  '24s.com',
  'luisaViaRoma.',
  'italist.',
  'modaoperandi.',
  'fwrd.',
  'shopbop.',
  'endclothing.',

  // --- Sportswear / activewear ---
  'nike.',
  'adidas.',
  'puma.',
  'reebok.',
  'newbalance.',
  'asics.',
  'vans.',
  'converse.',
  'underarmour.',
  'lululemon.',
  'gymshark.',
  'fabletics.',
  'aloyoga.',
  'outdoorvoices.',
  'patagonia.',
  'northface.',
  'columbia.',
  'on-running.',
  'salomon.',
  'merrell.',
  'teva.',
  'hoka.',

  // --- Footwear & sneakers ---
  'crocs.',
  'birkenstock.',
  'drmartens.',
  'footlocker.',
  'finishline.',
  'goat.',
  'stockx.',
  'snipes.',
  'jd-sports.',
  'champssports.',

  // --- Jewelry / watches / accessories ---
  'pandora.',
  'tiffany.',
  'cartier.',
  'rolex.',
  'tagheuer.',
  'omega.',
  'bulgari.',
  'breitling.',
  'longines.',
  'fossil.',
  'danielwellington.',
  'mvmt.',
  'swarovski.',
  'skagen.',
  'citizenwatch.',
  'seikowatches.',
  'cluse.',
  'apmmonaco.',

  // --- Eyewear ---
  'ray-ban.',
  'warbyparker.',
  'zennioptical.',
  'eyebuydirect.',
  'oakley.',
  'persol.',
  'mauijim.',
  'glassesusa.',
  'sunglasshut.',
  'smartbuyglasses.',

  // --- Bags & luggage ---
  'samsonite.',
  'tumi.',
  'awaytravel.',
  'rimowa.',
  'kipling.',
  'longchamp.',
  'coach.',
  'michaelkors.',
  'katespade.',
  'guess.',
  'dooney.',
  'toryburch.',
  'herschel.',
  'eastpak.',
  'jansport.',

  // --- Sustainable / indie brands ---
  'pactwear.',
  'tentree.',
  'girlfriendcollective.',
  'organicbasics.',
  'kotn.',
  'matethelabel.',
  'theslowlabel.',
  'cuyana.',
  'allbirds.',

  // --- Department stores / regionals ---
  'marksandspencer.',
  'houseoffraser.',
  'johnlewis.',
  'debenhams.',
  'myer.',
  'davidjones.',
  'century21stores.',
  'lordandtaylor.',
  'boscovs.',
  'argos.',
  'boots.',
  'very.co.uk',
  'next.co.uk',
  'next.',
  'peek-cloppenburg.',
  'galerieslafayette.',
  'otto.de',
  'aboutyou.',
  'bonprix.',

  // --- Resale / luxury marketplaces ---
  'vestiairecollective.',
  'grailed.',
  'theRealReal.',
  'rebag.',
  'vinted.',
  'poshmark.',
  'depop.',
  'thredup.',

  // --- Beauty & skincare (fashion adjacent) ---
  'sephora.',
  'ulta.',
  'glossier.',
  'lookfantastic.',
  'cultbeauty.',
  'elfcosmetics.',
  'fentybeauty.',
  'rarebeauty.',
  'morphe.',
  'kyliecosmetics.',
  'hudabeauty.',
  'charlottetilbury.',
  'narscosmetics.',
  'mac-cosmetics.',
  'clinique.',
  'lancome.',
  'diorbeauty.',
  'chanelbeauty.',
  'shiseido.',
  'loreal.',
];

/// Non-ecommerce domains to ignore or filter out.
const List<String> kBannedDomains = [
  'facebook.',
  'instagram.',
  'twitter.',
  'x.com',
  'pinterest.',
  'tiktok.',
  'linkedin.',
  'reddit.',
  'youtube.',
  'blogspot.',
  'wordpress.',
  'tumblr.',
  'medium.',
  'substack.',
  'weebly.',
  'wixsite.',
  'blog.',
  'quora.',
  'fandom.',
  'wikipedia.',
  'tripadvisor.',
  'bbc.',
  'cnn.',
  'nytimes.',
  'forbes.',
  'bloomberg.',
  'goodreads.',
  'soundcloud.',
  'deviantart.',
  'dribbble.',
  'artstation.',
  'behance.',
];
