# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  # Remove path_provider_foundation from GeneratedPluginRegistrant to fix iOS 18.6.2 crash
  # We use Directory.systemTemp instead which doesn't require a plugin
  registrant_path = File.join(File.dirname(__FILE__), 'Runner', 'GeneratedPluginRegistrant.m')
  if File.exist?(registrant_path)
    puts "Removing path_provider_foundation from GeneratedPluginRegistrant.m"
    registrant_content = File.read(registrant_path)
    registrant_content.gsub!(/\[PathProviderPlugin registerWithRegistrar.*?\];/, '// PathProviderPlugin removed to fix iOS 18.6.2 crash')
    registrant_content.gsub!(/#import <path_provider_foundation.*?>/, '// #import <path_provider_foundation/PathProviderPlugin.h> // Removed')
    File.write(registrant_path, registrant_content)
  end
end
