create table if not exists public.credit_purchase_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  transaction_id text not null,
  product_id text not null,
  credits_added integer not null check (credits_added > 0),
  purchased_at timestamptz not null default now(),
  source text not null default 'unknown',
  created_at timestamptz not null default now()
);

alter table public.credit_purchase_events enable row level security;

create unique index if not exists idx_credit_purchase_events_transaction_id
  on public.credit_purchase_events(transaction_id);

create index if not exists idx_credit_purchase_events_user_id
  on public.credit_purchase_events(user_id);

create or replace function public.credit_pack_amount_for_product(
  p_product_id text
)
returns integer
language plpgsql
immutable
as $function$
declare
  v_product text := lower(coalesce(p_product_id, ''));
begin
  if v_product = '' then
    return 0;
  end if;

  if v_product = 'com.snaplook.credits20'
      or v_product like 'com.snaplook.credits20:%' then
    return 20;
  elsif v_product = 'com.snaplook.credits50'
      or v_product like 'com.snaplook.credits50:%' then
    return 50;
  elsif v_product = 'com.snaplook.credits100'
      or v_product like 'com.snaplook.credits100:%' then
    return 100;
  end if;

  return 0;
end;
$function$;

create or replace function public.apply_credit_purchase(
  p_user_id uuid,
  p_product_id text,
  p_transaction_id text,
  p_purchased_at timestamptz default now(),
  p_source text default 'unknown'
)
returns table (
  success boolean,
  message text,
  credits_added integer,
  paid_credits_remaining integer
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_credits integer := public.credit_pack_amount_for_product(p_product_id);
  v_event_id bigint;
  v_current_credits integer;
begin
  if p_user_id is null then
    return query select false, 'Missing user id'::text, 0, 0;
    return;
  end if;

  if coalesce(trim(p_transaction_id), '') = '' then
    return query select false, 'Missing transaction id'::text, 0, 0;
    return;
  end if;

  if v_credits <= 0 then
    return query
    select
      false,
      format(
        'Unsupported credit product: %s',
        coalesce(p_product_id, 'null')
      )::text,
      0,
      0;
    return;
  end if;

  select users.paid_credits_remaining
  into v_current_credits
  from public.users
  where users.id = p_user_id;

  if not found then
    return query select false, 'User not found'::text, 0, 0;
    return;
  end if;

  insert into public.credit_purchase_events (
    user_id,
    transaction_id,
    product_id,
    credits_added,
    purchased_at,
    source
  )
  values (
    p_user_id,
    p_transaction_id,
    p_product_id,
    v_credits,
    coalesce(p_purchased_at, now()),
    coalesce(p_source, 'unknown')
  )
  on conflict (transaction_id) do nothing
  returning id into v_event_id;

  if v_event_id is null then
    return query
    select
      true,
      'Transaction already processed'::text,
      0,
      coalesce(v_current_credits, 0);
    return;
  end if;

  update public.users
  set
    paid_credits_remaining =
      coalesce(public.users.paid_credits_remaining, 0) + v_credits,
    updated_at = now()
  where public.users.id = p_user_id
  returning public.users.paid_credits_remaining into v_current_credits;

  return query
  select
    true,
    format('Granted %s credits', v_credits)::text,
    v_credits,
    coalesce(v_current_credits, 0);
end;
$function$;

grant execute on function public.credit_pack_amount_for_product(text)
  to anon, authenticated, service_role;

grant execute on function public.apply_credit_purchase(
  uuid,
  text,
  text,
  timestamptz,
  text
)
  to anon, authenticated, service_role;
